#include "caquicocu.h"

std::string get_answer(Verbe verb, Temps tense, Pronom pronoun)
{
    static const std::string
        table[(const int) Verbe::count]
             [(const int) Temps::count]
             [(const int) Pronom::count] =
    {
        {
            {
                "ai",
                "as",
                "a",
                "avons",
                "avez",
                "ont",
            },
            {
                "avais",
                "avais",
                "avait",
                "avions",
                "aviez",
                "avaient",
            },
            {
                "aurai",
                "auras",
                "aura",
                "aurons",
                "aurez",
                "auront",
            },
            {
                "eus",
                "eus",
                "eut",
                "eûmes",
                "eûtes",
                "eurent",
            },
            {
                "ai eu",
                "as eu",
                "a eu",
                "avons eu",
                "avez eu",
                "ont eu",
            },
            {
                "avais eu",
                "avais eu",
                "avait eu",
                "avions eu",
                "aviez eu",
                "avaient eu",
            },
            {
                "aurai eu",
                "auras eu",
                "aura eu",
                "aurons eu",
                "aurez eu",
                "auront eu",
            },
            {
                "eus eu",
                "eus eu",
                "eut eu",
                "eûmes eu",
                "eûtes eu",
                "eurent eu",
            },
            {
                "aurais",
                "aurais",
                "aurait",
                "aurions",
                "auriez",
                "auraient",
            },
            {
                "aurais eu",
                "aurais eu",
                "aurait eu",
                "aurions eu",
                "auriez eu",
                "auraient eu",
            },
        },
        {
            {
                "chante",
                "chantes",
                "chante",
                "chantons",
                "chantez",
                "chantent",
            },
            {
                "chantais",
                "chantais",
                "chantait",
                "chantions",
                "chantiez",
                "chantaient",
            },
            {
                "chanterai",
                "chanteras",
                "chantera",
                "chanterons",
                "chanterez",
                "chanteront",
            },
            {
                "chantai",
                "chantas",
                "chanta",
                "chantâmes",
                "chantâtes",
                "chantèrent",
            },
            {
                "ai chanté",
                "as chanté",
                "a chanté",
                "avons chanté",
                "avez chanté",
                "ont chanté",
            },
            {
                "avais chanté",
                "avais chanté",
                "avait chanté",
                "avions chanté",
                "aviez chanté",
                "avaient chanté",
            },
            {
                "aurai chanté",
                "auras chanté",
                "aura chanté",
                "aurons chanté",
                "aurez chanté",
                "auront chanté",
            },
            {
                "eus chanté",
                "eus chanté",
                "eut chanté",
                "eûmes chanté",
                "eûtes chanté",
                "eurent chanté",
            },
            {
                "chanterais",
                "chanterais",
                "chanterait",
                "chanterions",
                "chanteriez",
                "chanteraient",
            },
            {
                "aurais chanté",
                "aurais chanté",
                "aurait chanté",
                "aurions chanté",
                "auriez chanté",
                "auraient chanté",
            },
        },
        {
            {
                "suis",
                "es",
                "est",
                "sommes",
                "êtes",
                "sont",
            },
            {
                "étais",
                "étais",
                "était",
                "étions",
                "étiez",
                "étaient",
            },
            {
                "serai",
                "seras",
                "sera",
                "serons",
                "serez",
                "seront",
            },
            {
                "fus",
                "fus",
                "fut",
                "fûmes",
                "fûtes",
                "furent",
            },
            {
                "ai été",
                "as été",
                "a été",
                "avons été",
                "avez été",
                "ont été",
            },
            {
                "avais été",
                "avais été",
                "avait été",
                "avions été",
                "aviez été",
                "avaient été",
            },
            {
                "aurai été",
                "auras été",
                "aura été",
                "aurons été",
                "aurez été",
                "auront été",
            },
            {
                "eus été",
                "eus été",
                "eut été",
                "eûmes été",
                "eûtes été",
                "eurent été",
            },
            {
                "serais",
                "serais",
                "serait",
                "serions",
                "seriez",
                "seraient",
            },
            {
                "aurais été",
                "aurais été",
                "aurait été",
                "aurions été",
                "auriez été",
                "auraient été",
            },
        },
        {
            {
                "fais",
                "fais",
                "fait",
                "faisons",
                "faites",
                "font",
            },
            {
                "faisais",
                "faisais",
                "faisait",
                "faisions",
                "faisiez",
                "faisaient",
            },
            {
                "ferai",
                "feras",
                "fera",
                "ferons",
                "ferez",
                "feront",
            },
            {
                "fis",
                "fis",
                "fit",
                "fîmes",
                "fîtes",
                "firent",
            },
            {
                "ai fait",
                "as fait",
                "a fait",
                "avons fait",
                "avez fait",
                "ont fait",
            },
            {
                "avais fait",
                "avais fait",
                "avait fait",
                "avions fait",
                "aviez fait",
                "avaient fait",
            },
            {
                "aurai fait",
                "auras fait",
                "aura fait",
                "aurons fait",
                "aurez fait",
                "auront fait",
            },
            {
                "eus fait",
                "eus fait",
                "eut fait",
                "eûmes fait",
                "eûtes fait",
                "eurent fait",
            },
            {
                "ferais",
                "ferais",
                "ferait",
                "ferions",
                "feriez",
                "feraient",
            },
            {
                "aurais fait",
                "aurais fait",
                "aurait fait",
                "aurions fait",
                "auriez fait",
                "auraient fait",
            },
        },
    };


    if (verb == Verbe::null || verb == Verbe::count
    || tense == Temps::null || tense == Temps::count
    || pronoun == Pronom::null || pronoun == Pronom::count)
        return std::string("");

    return table[(int)verb][(int)tense][(int)pronoun];
}
